# 1-2. 산포 통계량

- 분산, 표준편차, 변동계수, 스케일링, 범위와 IQR을 계산해본다.

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

## 1. 분산 계산

In [2]:
# 분산을 계산할 데이터
x = [1, 2, 3, 4, 5]

# ddof=1: 표본분산, 분모가 n-1
print(np.var(x, ddof=1))

# ddof를 생략하면 0: 모분산, 분모가 n
print(np.array(x).var())

# Pandas Series로 모분산 계산
print(pd.Series(x).var(ddof=0))

2.5
2.0
2.0

In [3]:
x = [1, 2, 3, 4, 5]

mean = np.mean(x)              # 평균: 3
squared_deviations = (np.array(x) - mean) ** 2
variance = np.mean(squared_deviations)

print(squared_deviations)  # [4. 1. 0. 1. 4.]
print(variance)           # 2.0

[4. 1. 0. 1. 4.]
2.0

### np.var() 계산 과정 확인

`np.var(x)`가 분산을 계산하는 과정을 직접 풀어서 확인한다.

In [4]:
x = [1, 2, 3, 4, 5]

# 1. 데이터의 평균 계산
mean = np.mean(x)

# 2. 각 값에서 평균을 뺀 뒤 제곱
squared_deviations = (np.array(x) - mean) ** 2

# 3. 제곱한 편차들의 평균 = 모분산
variance = np.mean(squared_deviations)

print(f"평균: {mean}")
print(f"편차 제곱: {squared_deviations}")
print(f"직접 계산한 분산: {variance}")
print(f"np.var()로 계산한 분산: {np.var(x)}")

평균: 3.0
편차 제곱: [4. 1. 0. 1. 4.]
직접 계산한 분산: 2.0
np.var()로 계산한 분산: 2.0

### ddof의 의미

분산은 편차 제곱의 합을 `(데이터 개수 - ddof)`로 나눈 값이다.

- `ddof=0`: 데이터 개수 `n`으로 나눔 → 모분산
- `ddof=1`: 데이터 개수 `n-1`로 나눔 → 표본분산

표본으로 모집단의 분산을 추정할 때는 분산이 작게 계산되는 경향을 보정하기 위해 보통 `ddof=1`을 사용한다.

In [5]:
x = [1, 2, 3, 4, 5]

# 평균에서 떨어진 정도를 제곱한 값들의 합
squared_deviation_sum = np.sum((np.array(x) - np.mean(x)) ** 2)

# 모분산: 데이터 개수 n으로 나눔
population_variance = squared_deviation_sum / len(x)

# 표본분산: 데이터 개수 n - 1로 나눔
sample_variance = squared_deviation_sum / (len(x) - 1)

print(f"편차 제곱의 합: {squared_deviation_sum}")
print(f"모분산 (ddof=0): {population_variance}")
print(f"표본분산 (ddof=1): {sample_variance}")

print(f"np.var(x, ddof=0): {np.var(x, ddof=0)}")
print(f"np.var(x, ddof=1): {np.var(x, ddof=1)}")

편차 제곱의 합: 10.0
모분산 (ddof=0): 2.0
표본분산 (ddof=1): 2.5
np.var(x, ddof=0): 2.0
np.var(x, ddof=1): 2.5

### Pandas Series로 분산 계산

`Series`는 Pandas의 1차원 데이터 구조이다.
리스트를 `Series`로 바꾸면 Pandas 방식의 통계 함수를 사용할 수 있다.

In [6]:
x = [1, 2, 3, 4, 5]

# 리스트를 Pandas Series 형태로 변환
series = pd.Series(x)

print(series)

# ddof=0: 모분산, n으로 나눔
print(f"모분산: {series.var(ddof=0)}")

# ddof=1: 표본분산, n-1로 나눔
print(f"표본분산: {series.var(ddof=1)}")

0    1
1    2
2    3
3    4
4    5
dtype: int64
모분산: 2.0
표본분산: 2.5

## 2. 표준편차 계산

In [ ]:
x = [1, 2, 3, 4, 5]

# 표본표준편차: 분모가 n - 1
print(np.std(x, ddof=1))

# 모표준편차: 분모가 n
print(np.array(x).std(ddof=0))

# Pandas Series로 표본표준편차 계산
print(pd.Series(x).std(ddof=1))

### 표준편차의 계산 과정

표준편차는 분산에 제곱근을 씌운 값이다.
분산은 값의 단위가 제곱되므로, 실제 데이터 단위로 다시 보기 위해 제곱근을 사용한다.

표준편차 = √분산
### 표준편차란?

분산은 데이터가 평균에서 얼마나 퍼져 있는지 나타내지만,
값이 제곱되어 있어서 바로 이해하기 어렵다.

그래서 분산에 제곱근을 씌워 원래 데이터와 같은 기준으로 만든 값이 표준편차다.

예를 들어 점수의 표준편차가 1.41이라면,
점수들이 평균에서 대략 1.41점 정도 떨어져 있다고 이해할 수 있다.

In [ ]:
x = [1, 2, 3, 4, 5]

# 모분산: ddof=0이므로 n으로 나눔
population_variance = np.var(x, ddof=0)

# 모표준편차: 모분산의 제곱근
population_std = np.sqrt(population_variance)

print(f"모분산: {population_variance}")
print(f"직접 계산한 모표준편차: {population_std}")
print(f"np.std()로 계산한 모표준편차: {np.std(x, ddof=0)}")

## 3. 변동계수의 필요성

표준편차는 데이터의 크기에 영향을 받는다.
변동계수는 평균에 비해 데이터가 얼마나 퍼져 있는지 나타낸다.

변동계수 = 표준편차 / 평균

In [7]:
# x2는 x1의 모든 값을 10배로 만든 데이터
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

# 표본표준편차를 비교
print(np.std(x1, ddof=1))
print(np.std(x2, ddof=1))

1.5811388300841898
15.811388300841896

## 4. 변동계수 계산

변동계수는 표준편차를 평균으로 나눈 값이다.
값이 작을수록 평균에 비해 데이터가 덜 퍼져 있다.

In [8]:
# scipy의 변동계수 함수
print(stats.variation(x1))
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317

In [9]:
# stats.variation()은 기본적으로 ddof=0인 표준편차를 사용한다.
x1_coefficient = np.std(x1, ddof=0) / np.mean(x1)
x2_coefficient = np.std(x2, ddof=0) / np.mean(x2)

print(x1_coefficient)
print(x2_coefficient)

0.47140452079103173
0.4714045207910317

## 5. 스케일링

스케일링은 크기 범위가 다른 데이터를 비교하거나
머신러닝 모델에 넣기 쉽게 값을 변환하는 작업이다.

In [10]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

### 5-1. Standard Scaling

각 값이 평균에서 표준편차 기준으로 얼마나 떨어져 있는지 나타낸다.

In [11]:
# (값 - 평균) / 표준편차
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

### 5-2. Min-Max Scaling

가장 작은 값을 0, 가장 큰 값을 1로 변환한다.

In [12]:
# (값 - 최솟값) / (최댓값 - 최솟값)
minmax_x1 = (x1 - x1.min()) / (x1.max() - x1.min())
minmax_x2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(minmax_x1)
print(minmax_x2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

### 5-3. scikit-learn을 이용한 스케일링

scikit-learn은 머신러닝과 데이터 전처리에 사용하는 라이브러리다.

In [13]:
# X1은 1~5, X2는 10~50인 표 형태 데이터
X = pd.DataFrame({
    "X1": [1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]
})

X

   X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [14]:
from sklearn.preprocessing import MinMaxScaler

# 스케일러 객체 생성
scaler = MinMaxScaler()

# 데이터의 최솟값과 최댓값을 확인하고 0~1 범위로 변환
Z = scaler.fit_transform(X)

# 결과는 NumPy 배열이므로, 보기 좋게 DataFrame으로 변환
pd.DataFrame(Z, columns=["X1", "X2"])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

### 5-4. scikit-learn Standard Scaling

각 열의 평균을 0으로, 표준편차를 1로 맞추는 방식이다.

In [15]:
from sklearn.preprocessing import StandardScaler

# 표준 스케일링 도구 생성
standard_scaler = StandardScaler()

# 각 열을 평균 0, 표준편차 1 기준으로 변환
S = standard_scaler.fit_transform(X)

# 보기 좋게 DataFrame으로 변환
pd.DataFrame(S, columns=["X1", "X2"])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

## 6. 범위와 사분위 범위 계산

정규분포를 따라 무작위 데이터를 만든 뒤,
범위와 사분위 범위(IQR)를 계산한다.

In [16]:
# np.random.normal(평균, 표준편차, 데이터 개수)
x = np.random.normal(100, 20, size=1000)

# 데이터가 너무 많으므로 앞의 10개만 확인
print(x[:10])

[140.83475022  89.15883498  91.53207598 102.14010052  96.46652397
  67.65585693 137.56919424  92.97228693  99.50573138 115.18308432]

In [17]:
# np.ptp는 최댓값 - 최솟값을 계산한다.
print(np.ptp(x))

# 범위를 직접 계산한 방식
print(np.max(x) - np.min(x))

127.61957332965733
127.61957332965733

## 7. 사분위 범위(IQR) 계산

IQR은 3사분위수(Q3)에서 1사분위수(Q1)를 뺀 값이다.
이상치의 영향을 범위보다 덜 받는다.

In [18]:
# Q3(75% 지점) - Q1(25% 지점)
iqr_by_numpy = np.quantile(x, 0.75) - np.quantile(x, 0.25)

# SciPy 함수로 IQR 계산
iqr_by_scipy = stats.iqr(x)

print(iqr_by_numpy)
print(iqr_by_scipy)

27.869278976792756
27.869278976792756